/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#c3c6d7",
        "on-error-container": "#93000a",
        "tertiary": "#006242",
        "on-surface": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "on-background": "#0b1c30",
        "on-primary-fixed": "#00174b",
        "surface-variant": "#d3e4fe",
        "secondary": "#565e74",
        "secondary-container": "#dae2fd",
        "primary-container": "#2563eb",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary-container": "#007d55",
        "outline": "#737686",
        "secondary-fixed-dim": "#bec6e0",
        "on-tertiary-container": "#bdffdb",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "surface-tint": "#0053db",
        "background": "#f8f9ff",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container": "#e5eeff",
        "primary-fixed-dim": "#b4c5ff",
        "surface-bright": "#f8f9ff",
        "on-surface-variant": "#434655",
        "primary-fixed": "#dbe1ff",
        "surface-dim": "#cbdbf5",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#002113",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "inverse-primary": "#b4c5ff",
        "primary": "#004ac6",
        "on-secondary": "#ffffff",
        "inverse-surface": "#213145",
        "on-tertiary-fixed-variant": "#005236"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "1.0rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Lexend"],
        "body": ["Inter"],
        "label": ["Inter"],
        "sans": ['Inter', 'sans-serif'],
        "display": ['Lexend', 'sans-serif']
      }
    },
  },
  plugins: [],
}
